import {
    attribute,
    autoGeneratedHashKey,
    table,

} from '@aws/dynamodb-data-mapper-annotations';

import { v4 as uuidv4 } from 'uuid';
import { Models } from 'utilities-techsweave';

/*
 * This class rappresent a product item in products table
 */
@table(process.env.PRODUCTS_TABLE)
class Product implements Models.Tables.IProduct {
    @autoGeneratedHashKey()
    id: string;

    @attribute({
        defaultProvider: () => {
            return uuidv4();
        }
    })
    SKU: string;

    @attribute()
    title: string;

    @attribute()
    description?: string;

    @attribute()
    price: number;

    @attribute()
    discount?: number;

    @attribute()
    availabilityQta?: number;

    @attribute()
    imageURL?: string;

    @attribute()
    isSalable?: boolean;

    @attribute()
    categorieId?: string;

    @attribute()
    notes?: string;

    @attribute()
    tags?: string[];

    @attribute()
    customSpecs?: Models.Tables.ISpecValue[];


    async setSKU(): Promise<void> {
        //TODO finish with property values
        this.SKU = this.title.toUpperCase().substr(0, 3)
            .concat('-')
            .concat(this.categorieId.toUpperCase().substr(0, 3))
            .concat('-')
            .concat(this.description.toUpperCase().substr(0.3));
    }

}

export default Product;