import {
    attribute,
    autoGeneratedHashKey,
    table
} from '@aws/dynamodb-data-mapper-annotations';

import { Models } from 'utilities-techsweave';

/*
 * This class rappresent a product item in products table
 */
@table(process.env.PRODUCTS_TABLE)
class Product implements Models.Tables.IProduct {
    @autoGeneratedHashKey()
    id: string;

    @attribute()
    SKU: string;

    @attribute()
    title: string;

    @attribute()
    description?: string;

    @attribute()
    price: number;

    @attribute()
    discount?: number;

    @attribute()
    availabilityQta?: number;

    @attribute()
    imageURL?: string;

    @attribute()
    isSalable?: boolean;

    @attribute()
    categorieId?: string;

    @attribute()
    notes?: string;

    @attribute()
    tags?: string[];

    @attribute()
    customSpecs?: Models.Tables.ISpecValue[];

}

export default Product;